"""T1105 — Ingress Tool Transfer (simulation).

Real adversary technique: download a tool/payload from a C2 server into a
writable directory on the victim host (temp, user profile, etc.), then execute it.

Simulation: writes a clearly-labelled benign marker file to the system's temp
directory mimicking a freshly-dropped tool. No network activity, no executable
code dropped. cleanup() removes the marker.

The artifact path and name are designed to match common adversary staging
patterns (random hex name, .exe or .dll extension) so that EDR file-write
detections fire without any real threat.
"""
from __future__ import annotations

import os
import platform
import random
import string
import tempfile
import time
from pathlib import Path
from typing import Any

from ..base import TTP, TTPResult, registry


MARKER_BANNER = (
    "APT_SIMULATOR_BENIGN_TOOL_MARKER\n"
    "Simulated ingress tool transfer artifact. Not a real executable.\n"
    "Safe to delete. Generated by APT Simulator for detection validation.\n"
)


def _staging_dir() -> Path:
    base = os.environ.get("APT_SIM_MARKER_DIR")
    if base:
        return Path(base)
    return Path(tempfile.gettempdir())


def _random_hex(n: int = 8, rng: random.Random | None = None) -> str:
    src = rng or random
    return "".join(src.choices(string.hexdigits[:16], k=n))


class T1105IngressToolTransfer(TTP):
    attack_id = "T1105"
    name = "Ingress Tool Transfer (sim)"
    description = "Drops a benign marker file to temp/staging dir simulating a downloaded tool"
    tactic = "command_and_control"
    supported_platforms = ("windows", "linux", "darwin")

    def run(self, params: dict[str, Any]) -> TTPResult:
        started = time.time()
        rng = random.Random(params.get("seed"))
        ext = str(params.get("extension", ".exe"))
        if not ext.startswith("."):
            ext = "." + ext
        staging = _staging_dir()
        staging.mkdir(parents=True, exist_ok=True)
        fname = f"apt_sim_{_random_hex(8, rng)}{ext}"
        dest = staging / fname
        try:
            dest.write_text(MARKER_BANNER, encoding="utf-8")
        except OSError as exc:
            return TTPResult(ok=False, error=str(exc), started_at=started, finished_at=time.time())

        return TTPResult(
            ok=True,
            output=f"dropped marker tool to {dest}",
            artifacts=[str(dest)],
            started_at=started,
            finished_at=time.time(),
            extra={"dest": str(dest), "staging_dir": str(staging)},
        )

    def cleanup(self, params: dict[str, Any]) -> TTPResult:
        started = time.time()
        staging = _staging_dir()
        removed = 0
        for f in staging.glob("apt_sim_????????.*"):
            try:
                f.unlink()
                removed += 1
            except OSError:
                pass
        return TTPResult(
            ok=True,
            output=f"removed {removed} tool marker(s) from {staging}",
            started_at=started,
            finished_at=time.time(),
        )

    def sigma_rule(self) -> dict[str, Any]:
        return {
            "title": "Suspicious Executable Dropped in Temp Dir (APT Simulator T1105)",
            "id": "a1105000-0000-0000-0000-000000001105",
            "status": "experimental",
            "description": (
                "Detects executable files written to the system temp directory — "
                "a common staging location for downloaded tools and payloads."
            ),
            "references": ["https://attack.mitre.org/techniques/T1105"],
            "tags": ["attack.command_and_control", "attack.t1105"],
            "logsource": {"category": "file_event"},
            "detection": {
                "selection_win": {
                    "TargetFilename|contains": ["\\Temp\\apt_sim_"],
                    "TargetFilename|endswith": [".exe", ".dll", ".bat", ".ps1"],
                },
                "selection_posix": {
                    "TargetFilename|contains": ["/tmp/apt_sim_"],
                },
                "condition": "1 of selection_*",
            },
            "falsepositives": ["Legitimate installers staging to temp"],
            "level": "medium",
        }

    def synthetic_events(self, params: dict[str, Any], result: Any = None) -> list[dict[str, Any]]:
        if result and result.artifacts:
            path = result.artifacts[0]
        else:
            plat = platform.system().lower()
            if plat == "windows":
                path = "C:\\Windows\\Temp\\apt_sim_deadbeef.exe"
            else:
                path = "/tmp/apt_sim_deadbeef.exe"
        return [{"category": "file_event", "TargetFilename": path}]


registry.register(T1105IngressToolTransfer())
