from __future__ import annotations

from pathlib import Path

import ttps  # noqa: F401
from orchestrator.core.config import load_config
from orchestrator.dsl.loader import load_scenarios_from_dir
from ttps.base import registry


ROOT = Path(__file__).resolve().parents[1]
TEXT_SUFFIXES = {".md", ".py", ".js", ".css", ".html", ".yaml", ".yml", ".toml", ".txt"}
SKIP_PARTS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tmp",
    ".venv",
    "__pycache__",
}
FORBIDDEN_MARKERS = [
    "co" + "dex",
    "open" + "ai",
    "chat" + "gpt",
    "ai" + "-generated",
    "generated by " + "ai",
    "artificial" + " intelligence",
]


def test_exact_public_counts() -> None:
    cfg = load_config("config/default.yaml")
    scenarios = load_scenarios_from_dir(cfg.orchestrator.scenarios_dir)
    assert len(registry.all()) == 5064
    assert len(scenarios) == 3522
    assert len(list((ROOT / "scenarios" / "generated").glob("*.yaml"))) == 2500
    assert len(list((ROOT / "scenarios" / "ael").glob("*.yaml"))) == 11
    assert len(list((ROOT / "scenarios" / "validated").glob("*.yaml"))) == 1000
    assert sum(1 for _ in (ROOT / "evidence" / "soc_golden_events.jsonl").open(encoding="utf-8")) == 2000


def test_readme_states_exact_counts() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    for expected in [
        "5,064 TTPs",
        "3,522 loaded scenarios",
        "11 classic YAML scenarios",
        "2,500 generated YAML scenarios",
        "11 emulation-plan YAML scenarios",
        "1,000 validated actor-chain YAML scenarios",
        "2,000 SOC golden event rows",
        "15,680,015,680 generable scenario variants",
        "5,064 Sigma rules",
        "11 enterprise validation tracks",
        "3 agent package targets",
        "5 load-test profiles",
        "4 SIEM validation targets",
        "15/15 current ATT&CK Enterprise tactics covered",
        "696 current ATT&CK Enterprise base technique/sub-technique IDs",
        "100 ATT&CK-mapped marker-only variants",
        "4,149 ATT&CK scale variants",
        "36 Cloud/Kubernetes lab TTPs",
        "28 Active Directory/Windows enterprise lab TTPs",
    ]:
        assert expected in readme


def test_public_files_do_not_include_forbidden_markers() -> None:
    for path in ROOT.rglob("*"):
        if any(part in SKIP_PARTS for part in path.parts):
            continue
        if not path.is_file() or path.suffix.lower() not in TEXT_SUFFIXES:
            continue
        text = path.read_text(encoding="utf-8", errors="ignore").lower()
        for marker in FORBIDDEN_MARKERS:
            assert marker not in text, f"{marker!r} found in {path.relative_to(ROOT)}"
