"""ATT&CK Navigator Layer Export.

Generates a MITRE ATT&CK Navigator v4.x layer JSON from the registered TTP
library and optional run history from the SQLite database.

Layer colour coding:
  - #3fb950 (green)  — Sigma rule present AND last run was success
  - #58a6ff (blue)   — Sigma rule present, no run history yet
  - #d29922 (amber)  — TTP simulated but no Sigma rule
  - #8b949e (grey)   — registered but excluded from current platform

Usage:
    python -m orchestrator.navigator_export export --out navigator_layer.json
    python -m orchestrator.navigator_export export --db data/apt_sim.db --out layer.json

API endpoint:
    GET /coverage/navigator         → returns the layer JSON directly
    GET /coverage/navigator?pretty=1 → human-readable JSON
"""
from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any

import typer

import ttps  # noqa: F401  (trigger TTP self-registration)
from ttps.base import registry


# ATT&CK tactic shortname used in Navigator (hyphenated).
_TACTIC_MAP: dict[str, str] = {
    "reconnaissance": "reconnaissance",
    "resource_development": "resource-development",
    "initial_access": "initial-access",
    "execution": "execution",
    "persistence": "persistence",
    "privilege_escalation": "privilege-escalation",
    "defense_evasion": "defense-evasion",
    "credential_access": "credential-access",
    "discovery": "discovery",
    "lateral_movement": "lateral-movement",
    "collection": "collection",
    "command_and_control": "command-and-control",
    "exfiltration": "exfiltration",
    "impact": "impact",
}

# Colour palette
_C_COVERED = "#3fb950"   # green  — rule + run success
_C_RULE_ONLY = "#58a6ff"  # blue   — rule, no run yet
_C_SIM_ONLY = "#d29922"   # amber  — sim, no rule
_C_EXCLUDED = "#8b949e"   # grey   — platform mismatch


def _last_run_status(attack_id: str, db_path: str | None) -> str | None:
    """Return 'success' | 'failed' | None from the most recent run step."""
    if not db_path:
        return None
    p = Path(db_path)
    if not p.exists():
        return None
    try:
        from orchestrator.storage.db import Repository, init_engine  # local import to avoid circular
        repo = Repository(init_engine(db_path))
        runs = repo.list_runs()
        best: str | None = None
        for run in runs:
            for step in repo.steps_for_run(run.id):
                if step.attack_id == attack_id:
                    if step.status == "success":
                        return "success"
                    best = step.status
        return best
    except Exception:
        return None


def build_layer(db_path: str | None = None) -> dict[str, Any]:
    """Build and return the Navigator layer dict."""
    techniques: list[dict[str, Any]] = []
    all_ttps = registry.all()

    for attack_id, ttp in sorted(all_ttps.items()):
        has_rule = ttp.sigma_rule() is not None
        run_status = _last_run_status(attack_id, db_path)
        tactic_nav = _TACTIC_MAP.get(ttp.tactic, ttp.tactic.replace("_", "-"))

        if has_rule and run_status == "success":
            color = _C_COVERED
            score = 100
            comment = "Covered — Sigma rule present, last run: success"
        elif has_rule:
            color = _C_RULE_ONLY
            score = 75
            comment = f"Detection rule present. Last run status: {run_status or 'not yet run'}"
        else:
            color = _C_SIM_ONLY
            score = 40
            comment = "TTP simulated — no Sigma detection rule yet"

        entry: dict[str, Any] = {
            "techniqueID": attack_id,
            "tactic": tactic_nav,
            "color": color,
            "comment": comment,
            "enabled": True,
            "score": score,
            "metadata": [
                {"name": "sigma_rule", "value": "yes" if has_rule else "no"},
                {"name": "platforms", "value": ", ".join(ttp.supported_platforms)},
                {"name": "last_run", "value": run_status or "—"},
            ],
        }
        techniques.append(entry)

    layer: dict[str, Any] = {
        "name": "APT Simulator Coverage",
        "versions": {
            "attack": "14",
            "navigator": "4.9.1",
            "layer": "4.5",
        },
        "domain": "enterprise-attack",
        "description": (
            f"Auto-generated by APT Simulator on {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}. "
            f"Shows {len(techniques)} simulated TTPs with Sigma rule and run status."
        ),
        "filters": {
            "platforms": ["Windows", "Linux", "macOS", "IaaS"],
        },
        "sorting": 3,
        "layout": {
            "layout": "side",
            "aggregateFunction": "average",
            "showID": True,
            "showName": True,
            "showAggregateScores": True,
            "countUnscored": False,
            "expandedSubtechniques": "annotated",
        },
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {
            "colors": ["#ff6666", "#ffe766", "#8ec843"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "Covered (rule + run success)", "color": _C_COVERED},
            {"label": "Rule present (not yet run)", "color": _C_RULE_ONLY},
            {"label": "Simulated (no rule)", "color": _C_SIM_ONLY},
        ],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#1c2128",
        "selectTechniquesAcrossTactics": False,
        "selectSubtechniquesWithParent": False,
        "metadata": [
            {"name": "generator", "value": "APT Simulator"},
            {"name": "ttp_count", "value": str(len(techniques))},
        ],
        "links": [
            {"label": "APT Simulator Docs", "url": "http://localhost:8000/docs"},
        ],
    }
    return layer


app = typer.Typer(no_args_is_help=True)


@app.callback()
def _root() -> None:
    """ATT&CK Navigator layer export."""


@app.command()
def export(
    out: str = typer.Option("navigator_layer.json", help="Output file path"),
    db: str = typer.Option("data/apt_sim.db", help="SQLite DB path for run history"),
    pretty: bool = typer.Option(True, help="Pretty-print JSON"),
) -> None:
    """Export an ATT&CK Navigator layer JSON from registered TTPs and run history."""
    layer = build_layer(db_path=db if Path(db).exists() else None)
    out_path = Path(out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    indent = 2 if pretty else None
    out_path.write_text(json.dumps(layer, indent=indent, ensure_ascii=False), encoding="utf-8")
    typer.echo(f"Navigator layer written to {out_path}  ({len(layer['techniques'])} techniques)")


if __name__ == "__main__":
    app()
